spring:
  application:
    name: job-tracker
  datasource:
    url: jdbc:mysql://localhost:3306/jobtrackerdb?useSSL=false&serverTimeZone=America/Chicago
    username: root
    password: Marine_Soccer9
    driver-class-name: com.mysql.cj.jdbc.Driver